### ISSUE TITLE
missing files in npm module

### ISSUE THREAD

**Issue by Misaghlb** [abbas-oveissi/generator-helma-mvp#1]
hi abbas
two files in npm module are missing:
generator-helma-mvp/generators/app/templates/gradle.properties
generator-helma-mvp/generators/app/templates/.gitignore

**Comment by abbas-oveissi** [comment]
<div dir="rtl">
سلام

اون فایل gradle.properties نمیدونم چرا به پروژه اضافه نشده بود. اضافه کردمش.
قضیه فایل .gitignore یکم پیچیده‌تر بود. انگار npm این فایل‌ رو جزء پکیج حساب نمیکنه. واسه همین مجبور شدم که اسم‌هاشون رو به _gitignore تغییر بدم و توو فرآیند کپی کردنشون، اسم‌هارو درست کنم.
الان نسخه‌ی 0.0.2 رو منتشر کردم. آخرین نسخه رو نصب کنید، ببینید مشکل حل میشه یا نه

**Comment by Misaghlb** [comment]
حل شد
