### ISSUE TITLE
کامل نبودن کامند‌های npm

### ISSUE THREAD

**Issue by aminone** [abbas-oveissi/generator-helma-mvp#2]
تا جایی که من می‌دونم وقتی از سوییچ g استفاده میشه کامند باید با سودو ران بشه

```
sudo npm install -g yo
sudo npm install -g generator-helma-mvp
```

**Comment by abbas-oveissi** [comment]
توی داکیومنت ابزار یومن خونده بودم که نباید از سودو استفاده کرد.واسه همین منم دیگه ننوشتمشون.
گفته بود بجاش از این آموزش استفاده کنید:
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by aminone** [comment]
ممنون
